
classes:
- system.linux.system.single
- system.openssh.server.team.lab
- system.openssh.server.team.tcpcloud
- system.openssh.server.team.mcp_qa
- system.openssh.server.team.l1_support
- system.openssh.server.team.l2_support
- cluster.scale-test.openstack
- cluster.scale-test.cicd
parameters:
  _param:
    salt_control_trusty_image: http://apt-mk.mirantis.com/images/ubuntu-14-04-x64-mcp1.0.qcow2
    salt_control_xenial_image: http://apt-mk.mirantis.com/images/ubuntu-16-04-x64-mcp1.0.qcow2

    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 172.16.44.155
    infra_config_deploy_address: 172.16.44.155

    cluster_domain: local.lan
    cluster_name: scale-test
    cluster_public_host: ${_param:openstack_proxy_address}
    infra_kvm_address: 172.16.44.160
    infra_kvm_node01_address: 172.16.46.27
    infra_kvm_node02_address: 172.16.46.28
    infra_kvm_node03_address: 172.16.46.29
    infra_kvm_node01_deploy_address: 10.11.0.101
    infra_kvm_node02_deploy_address: 10.11.0.102
    infra_kvm_node03_deploy_address: 10.11.0.103
    infra_kvm_node01_hostname: kvm01
    infra_kvm_node02_hostname: kvm02
    infra_kvm_node03_hostname: kvm03

    glusterfs_node01_address: ${_param:infra_kvm_node01_address}
    glusterfs_node02_address: ${_param:infra_kvm_node02_address}
    glusterfs_node03_address: ${_param:infra_kvm_node03_address}

    control_network_netmask: 255.255.252.0
    tenant_network_netmask: 255.255.255.0
    control_vlan: 2
    tenant_vlan: 1101

    dns_server01: 8.8.8.8
    dns_server02: 8.8.4.4
    deploy_network_netmask: 255.255.255.0
    deploy_network_gateway: 10.11.0.254

    linux_dhcp_interface:
      enabled: true
      type: eth
      proto: dhcp
    linux_single_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:single_address}
      netmask: ${_param:control_network_netmask}
      name_servers:
        - ${_param:dns_server01}
        - ${_param:dns_server02}

  salt:
    minion:
      trusted_ca_minions:
        - cfg

  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_kvm_node01_address}
          names:
          - ${_param:infra_kvm_node01_hostname}
          - ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_kvm_node02_address}
          names:
          - ${_param:infra_kvm_node02_hostname}
          - ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_kvm_node03_address}
          names:
          - ${_param:infra_kvm_node03_hostname}
          - ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
