
classes:
- system.linux.system.single
- system.openssh.server.team.lab
- system.openssh.server.team.tcpcloud
- system.openssh.server.team.mcp_qa
- system.openssh.server.team.l1_support
- system.openssh.server.team.l2_support
- cluster.scale-test.openstack
- cluster.scale-test.cicd
parameters:
  _param:
    salt_control_trusty_image: http://apt-mk.mirantis.com/images/ubuntu-14-04-x64-mcp1.0.qcow2
    salt_control_xenial_image: http://apt-mk.mirantis.com/images/ubuntu-16-04-x64-mcp1.0.qcow2

    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 10.3.63.238
    infra_config_deploy_address: 10.3.63.238

    cluster_domain: local.lan
    cluster_name: scale-test
    cluster_public_host: 10.3.56.200
    infra_kvm_address: 10.3.63.245
    infra_kvm_node01_address: 10.3.56.200
    infra_kvm_node02_address: 10.3.56.48
    infra_kvm_node03_address: 10.3.59.48
    infra_kvm_node01_deploy_address: 10.10.0.241
    infra_kvm_node02_deploy_address: 10.10.0.242
    infra_kvm_node03_deploy_address: 10.10.0.243
    infra_kvm_node01_hostname: kvm01
    infra_kvm_node02_hostname: kvm02
    infra_kvm_node03_hostname: kvm03

    glusterfs_node01_address: ${_param:infra_kvm_node01_address}
    glusterfs_node02_address: ${_param:infra_kvm_node02_address}
    glusterfs_node03_address: ${_param:infra_kvm_node03_address}

    control_network_netmask: 255.255.248.0
    tenant_network_netmask: 255.255.255.0
    control_vlan: 130
    tenant_vlan: 159

    dns_server01: 8.8.8.8
    dns_server02: 8.8.4.4
    deploy_network_netmask: 255.255.0.0
    deploy_network_gateway: 10.10.0.52

    linux_dhcp_interface:
      enabled: true
      type: eth
      proto: dhcp
    linux_single_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:single_address}
      netmask: ${_param:control_network_netmask}
      name_servers:
        - ${_param:dns_server01}
        - ${_param:dns_server02}

  salt:
    minion:
      trusted_ca_minions:
        - cfg

  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_kvm_node01_address}
          names:
          - ${_param:infra_kvm_node01_hostname}
          - ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_kvm_node02_address}
          names:
          - ${_param:infra_kvm_node02_hostname}
          - ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_kvm_node03_address}
          names:
          - ${_param:infra_kvm_node03_hostname}
          - ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
